spec:
  template:
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: "-Dswarm.project.stage.file=file:///app/config/project-defaults.yml"
        volumeMounts:
        - name: config
          mountPath: /app/config
      volumes:
      - name: config
        configMap:
          name: app-config
