metadata:
  name: app-config
  # workaround for https://github.com/fabric8io/fabric8-maven-plugin/pull/1805
  annotations: {}
data:
  project-defaults.yml: |
    greeting:
      message: Hello %s from a ConfigMap!
